---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-gmail
  namespace: monitoring
spec:
  encryptedData:
    app-password: AgBAZWihG5Fmx7btCgn95+GTs98uQEh+/brkyOvzpnEMfB+MO/Z4bt2mJqlJDxl3oTI1r7Bn4zWUF5K9UNuV+PY/hNQwI9Q5pEEVwwxB86fyGAqaXVKICafVIwKDu/n+BKbdMoxCFZr3i64KFeAsEfJP4kls6BqOCxZTxHCkDZOZWmOijSQL4ggpiYcCDtmBuO9Qfl0ICy/NBDb3PuEdTG3eFhpix8dfgHQYO3kSI4IAVks/yrU5ctqO+rhHnx/B64tEPvqo4JqjHvBY2PRf/T90UqAio8mFfgjArn7J2UZvvDxGpLgSovMgv6AloID0KnW1otTcSd2FKNY1mW3nNXrej8EZnS2KNAaV9Y2Jw4H9RrtOJX7+Nx+lNQ7UlYnxZjhdi+Nv0lUla6eho47Zm6uiNPoSNkHNO62PmBKaa2EhXYXcAW9sgDKcsSfrYFqLyZgzz0PxVuEFDHFIB42jmRLt56KEuUgNuZe30XAsem/amQkYWKWD7w3/ptfhvEEbPeh2hoO+ldEYv496/d+HiH4c8MCaECSjLuVVxBIncbd7nL5jc4YM0kw16eh+HMfAuduTjTF/2MRB1Wf7XwsX4Je8JGq/MXHD4NAdvC6QP3LCqlvZiysOF5BxTwCq9C4+OHQfFnYj92wPoS3hkT9YlStqBkQh5h+Nrds25EO5c1dpP2FcaOliHTgik5Ea7VieKAtchgMcjoVg6po53F6a6bkktb3J
    email: AgCoijG0oU4Bf6KTwP5+yyCg5EvkfVPzhlTxIkAagpYZYYRq6M8KQSU/isZWl3KPpGdMX9nkK1p5ItvM7wxhoKWKPf8Dm+M75w1a6gkzddNo1RRhbKWXjOd2I5UIvV/c5/ae23/aglCM2ZCZS/yqrhVM6OzNBu+4BOrYLFHagTTrJ9L6vJxph8bycMTk9wHfKHpYn8phVRgRqpSjD6QSqzX4nnbl6yPrcuItUlyJXC2jHOoLkgqbBDkNEyphfX0y0EC2IhKaBj/FGlpQfyj7hZbSBwBwvvGC9Bb3tvYuj2DLJe+tdf/mvQlE1xc3v+wnuXtjZcWRCe6XStqQm9iXqL2QdOXc9wFFLsmVRTODKAqOceK5kvx7C44etyeGV/hxzup7c6thudXPwbLoY0ggTr9Gmkg4lXiOB3dOm9eCMS6+tryKbq86scqTwR/XZ5cLd8jeze8qrDGQYLrgZxQmMNGmAAtcOCQBZ2fQrf7WfxT7UwV+K4dPCXUXoe9krrtQ00D7sfTYyeanrIQ/uP39+D3YSKNuWnjXn4w6iVSmLh4xR6yE7CO7XETpOWwza+/OV5DP2Vc3h3IKmU/Yr/HKr77MxLeDXnGuMtGpgCLTG0oLv1h90nXbkYG67UiEeB9CrSYDaAlbQ3yZ4eDuiv8ygfOWEhfz+Z6Igb89Iy+2Yl2mnvBB81PhsOJR5RwQmKV2nvCZhc+I+aViI9Dms4o97hLZGHNZqJK0lA==
  template:
    metadata:
      name: alertmanager-gmail
      namespace: monitoring
