---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-gmail
  namespace: monitoring
spec:
  encryptedData:
    app-password: AgAkm785DSmqpWNmxT5GTEmvly4nMe3/YwgcelglEd2GCeIeTznpjJiQwaddFkS7cI0SLG0sn0VQUERZ9SNEaS/h/RGItroFRw6moMxnm1PqRGMBxHwMzmXXeJNeUBLjeMaRA/ttAfdpXStLW2ATbpt/ASwHS7VICyZ/pQqIGOakSuybnEqnnmAJy8HSc0fcVlRxrX3OzgC3RPRkgBJfp1AhGwaZT96B1xFxKiYxoK+mWenehIr1u8Yh1ppUD3aEtr4wmv3JuXZgv93MIPM/oP5yLYqgrMKya5NuBNNJaKhTd6VXuy2fk4NkLwbcoGw201kRyu38JJweDMJ9Mpb8LapKQZGny3iEzECIOeRZSPF+0mdDy0BJtMvJ/XIzTXIsFjHryZ+PbKOQvKb9T/MX8gyQuSJ/qD7EyuSacDlgO+rjHWtgJb59Hmxf22HJPfwZ43DhyRQyOSv+mFafVdaP2OxPxE4RCWUyFYeRjLXgrf0R1QQr911Cw/k9KT9/vNcrbrbj/Qp3wQ8teatXzQHL05MagOVzfzp2ZIwbYoVI1kO+zZnry/05C5iEqxa67Q894pIvX7mBCn1vYsEn12r7w5j+al1CClVLtLEmznzF3mu5Z1hnSysN3zR2Mn+40Y+MWlHuvc22p/+/jhsZeJTQDDl7OnWRqrnWXb9VE6REjGmiToCbdjYNaElkudZZ4C3jBM4NT3n0/RWfNQ6gCuViQSA0F8kg
    email: AgA5WEdC7pdI3s+9oN6FCU1JA/77+cgu0rjToIKY5tXv7MDqgiwDbzWAuTjaLwp8Q4A+4cwMKLiZFOjPSU8GpltMvHXRmNx2kVAnojoG5z0OPM/m6/vp8tMXAx4ISZqBCM66TeKm8k9LvSS/+qrEdMd5YJnylyW5XWxMnkV/xfMqLCVA+0gaGL5cYQ71HM6N2/NKa5TZdosVwMYxyxgaGDcKrPfwjqseDS7+A5kFTZ5QfSPJHsPC8h1Bjmjx4ecJEekWWj2/tGPguKzVT7NwfTVxbKs7NkKxu8L5hiUcm3Fa8i7klHTN6C+9ZQNwjKV/JBTgsqJwwFcNmsTu7G8u1t2CO+p6UbfnIHIV5gnbNSaz1BcMJRwxZ89CSt92e0xB+MZrhT8WL/pfj64Y0lG/fgpak33EkMrEndkdcER98qebdox1NjPeen4tNeJG+t0bv50UrFucIFcef3iX1AyHJsLj+CNwL4ZGUGn5SX7LknEXUfp/t0t7N+gqCqLmxO5duOgX570LUArlSdYbTOh/k34HkPXCJ7YqWUxIf9pzNphC4HS77cii5SZKn4QklC6ktlQjjtlYChcHjgq1NltxRhDCgRZ+kTXQ+GFZsPDUjtyRSjNuzHxo1pgr5Mgg36rssPhcwbOXZDBtB5ao3BkKPvMWb6tfN1oyEXtPEqDEOZfy+FfyV0D04LOCNv+gYjJ6v984Ol4wzPRIcOlMbXVkrQCDOh+O8e+SiQ==
  template:
    metadata:
      name: alertmanager-gmail
      namespace: monitoring
    type: Opaque
