---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-gmail
  namespace: monitoring
spec:
  encryptedData:
    app-password: AgCsXH9lPk3kADK71/xAnIsKDOIfS0sgEZVkcwYbHzoyRqapyo2wrrjxDmlJcorSsl3IqFqA2kO5j8WAiCPDpspKCENaYomOPcVBL6XFExtR76bApIbR37pieLrRJ5Lok2a1PvInDNNJgG9eYFFRFuZi9ydLwHZU/itOxUZ1H9O+CuVmZjOo3uLFZ3jyvt1p0yCQHzMJZnThcBWFKqWgyqyxpXCSyeEVw1RwOKxkDteo5CyhScIp4Mr9l8/kff8245GQj61oHUg+KQWWcv23zZLq0yEbMOaOfGAMeeas1Z0OiOe0+zEkbJYK8Vq/eRYTR3aTljnVgbL4cmDdxuWV1lLfs+QBO0ui6+I7BxzWk4RgU0SvDDbCDwm0wV+lP9Wg7swg5YT8dFTy2lXmt+WZRE1my1B4Pd0QdKqaF0+t9AMbUJfJXSkPRB/8IhWAleUk7y1l301jea3tfrlYJxhbNiblIvE+GMNEWRFAYSK7lwk73yCouXc8u49GtCB+7wbEuInOEIEMI6UWwnwGAD3IgT+xuEkDRW7ioVJPRyvhzSLi1gufHmo50dFspM1b31p3GHjLZxYSePmruFC7PgzD/Ae07Zmo4f9+R82Dvb21WLL5kvuU5NOeApjhybiKjYVprNte2usGpnGgGFqfM7ZRwOvVXa/3d3jXtPDbD4KjzeHJz5JPj2sqrdR51SIYCs1dXrkXctB7sLwRGmJPxaeBRR1t
    email: AgBxfEL4VunYqoz2J35zRGGOEJ7w/rva2vbcJhMjWPmV2mdOkynTL/al0CTi5IohUxwJOdleQ7TcswsYYnCpjUEW95ZLwgChUycEaIj9P57MgciLabHkjcKBOuGoVgmpS+/F9UKf3FMME/UN8tXnOxtK4DUcBnNCab1yg/48+2AMbMpXLR1wtaPVyLxdKQORJKG1P15GGcU/iPJ9LGNPr+9RlZADA5/UFK6RfUclvgKoGds+7SdUcFxeXoifoSf9wrpkwjo4MtYnHYBsmrWXQlyBS+tGzKOqFM1U7xSvxwbv4H7Eqep/UfaY6bvVyj8E/YVJY+YiJQ740DFtB4csv7wQ899tNydt0yrCSEWoJkqPIRJSHbEv2SnyR2NuoumUUuwEMCOHWDr6gn/DVCpBswtcVL6pcCysWNhkKfha2ZBkh3kzgsJFUNSycR2gFmYIZpPUD5BviqcUXeVV0KpKS9MkH4yFuvB9Sg+EQdGP+p8dyMOS8/gyz2AFyxocQfE+Dz1oYxfnk3uWxVqOPhi9PFYKDuEZr1u5Ac7RyAaNFEdS3058mQPQl7aRpfX1rvAConM/Ju0IbEcT58U3CGXH+dbJwS63Poz4RcKlHYQ83bvFhUN0YbG6pb94Sc/aKOskhtXWGq4ieZWrW3kPDdVceGoXV8JPDEMmCwECPeCCO+4b+9aouc437cftQUrK0S+lAdf7s29hIoK/SnpnleSVgrgwwKaab+XTXw==
  template:
    metadata:
      name: alertmanager-gmail
      namespace: monitoring
