apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: 0.3.82
      helm:
        valueFiles:
          - $values/homeassistant/homeassistant-values.yaml
    - repoURL: https://github.com/pakube999/lab.git
      targetRevision: feature/homeassistant-cicd
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
