replicaCount: 2

persistence:
  - name: homarr-config
    enabled: true
    storageClassName: "local-path"
    accessMode: "ReadWriteOnce"
    size: "50Mi"
    mountPath: "/app/data/configs"
  - name: homarr-database
    enabled: true
    storageClassName: "local-path"
    accessMode: "ReadWriteOnce"
    size: "50Mi"
    mountPath: "/app/database"
  - name: homarr-icons
    enabled: true
    storageClassName: "local-path"
    accessMode: "ReadWriteOnce"
    size: "50Mi"
    mountPath: "/app/public/icons"
