service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 3000

# --- No persistence needed ---

persistence:
  config:
    enabled: false

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "192.168.1.9:3000,192.168.1.10:3000"   # <-- replace with your actual node IP

  - name: HOMEPAGE_VAR_PLEX_TOKEN
    valueFrom:
      secretKeyRef:
        name: homepage-plex-token
        key: PLEX_TOKEN

  - name: HOMEPAGE_VAR_TECHNITIUM_TOKEN
    valueFrom:
      secretKeyRef:
        name: homepage-technitium-token
        key: TECHNITIUM_TOKEN

  - name: HOMEPAGE_VAR_GRAFANA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: grafana-admin-password
        key: admin-password


enableRbac: true
serviceAccount:
  create: true

config:

  kubernetes:
    mode: cluster

  settings:
    title: PA Cluster
    description: My awesome homepage
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    blur: xl # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 50 # 0-100
    layout:
      Monitoring:
        style: row
        columns: 1
      Network:
        style: row
        columns: 1
      Media:
        style: row
        columns: 1
      Home-Atomation:
        style: row
        columns: 1

  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true


  services:
    - Network:
        - Technitium DNS:
            icon: technitium.png
            href: http://192.168.1.6:5380
            description: Local DNS server
            widget:
              type: technitium
              url: http://192.168.1.6:5380
              key: "{{HOMEPAGE_VAR_TECHNITIUM_TOKEN}}"

    

    - Monitoring:
        - Grafana Dashboard:
            widget:
              type: iframe
              src: "http://192.168.1.9:4000/public-dashboards/99198e1ea1554f288af492a3888e6ff9?viewPanel=panel-1"
              classes: "h-[800px] w-full"

        - Grafana:
            icon: grafana.png
            href: http://192.168.1.9:4000
            decription: grafan instance
            widget:
              type: grafana
              version: 2 # optional, default is 1
              alerts: alertmanager # optional, default is grafana
              url: http://192.168.1.9:4000
              username: admin
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}" 

        - Prometheus:
            icon: prometheus.png
            widget:
              type: prometheusmetric
              url: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
              refreshInterval: 10000
              metrics:
                - label: Active Alerts
                  query: alertmanager_alerts{state="active"}
                - label: CPU Usage
                  query: round(avg(1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100, 0.1)
                  format:
                  type: percent
                - label: Memory Used
                  query: node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes
                  format:
                    type: bytes

    - Media:
        - Plex:
            icon: plex.png
            href: http://192.168.1.10:32400/web
            description: Media server
            widget:
              type: plex
              url: http://192.168.1.10:32400
              key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"

    - Home-Automation:
        - homeassistant:
            icon: homeassistant.png

              # this might need the server running in back ground??
