---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-secrets
  namespace: media
spec:
  encryptedData:
    ND_LASTFM_APIKEY: AgAsDBVsXzvhtVn3+In35Fw3DbMbk0robibDuHjCc3x6Gth/kNdmilCSUIVA0egAPcBYTqXvFEyAf+d+IL5ofEXSDeLhea3Lh7MvGlxqoDj1rksMZiiuX5ZdGmI1KDUYdNYoMfqkQh0zJg+Bf/JXN0CMpOP7P/Yo2Pfa433YS/JV7HuduWbLgBi7PcMf/H6w3zrtSAF5Hs76FJrGO6npcOJQCNaxzVOMuWtJtFrw4BXQ5c1ulbmHPrFCk6SxTs1qpqAagG0dkG+15gz9ZG3t4EwqH26HtJx22TA0GtanqXtDh6eMaHuyL4k4ihmrY5HRnc01/K9wVtLcErYvUCV1JRUaf5Hqnx0VO0HIO5JDyv26NFqVKDaVwiv7Uif4+aW/XfhX60+wWK8gfEuz2O8DVmbtbIhtNqH3i0uV7Q1Yq5sJWEbnu920iRZPpYgqnJcFZZEUQasHJO6wqeGbZFPMI5lLISKWwyrbGghRUOQTEAJQnGrbBRuuYwBRMqIIBhhiMOz6JpwLgvN3s8R6V357f8G/F5qvRPIqb9hRh2aCCRNrkrmi5/g7db89QrY09zcelLldwtaNziq17x3GZnfIb3/jHPLGMI8+OMIjOSXSjSVseXxi1Ikl8NO/ADJbbwxHDlCiafVe/yKlO3bezxrWF6dNxQl3zCy2pT8A8IECgNJv9vY6zJ85z3FM68maygVFOBzggIk6KbTEKat9BBxMZRneXFvnL302kLYG2cSpfh1z+w==
    ND_LASTFM_SECRET: AgCgrp7pmgxlxhGSEpE6RXqKHYbDa2KiJ8DfIEZTIbqAI7pc0DvdBInAbir9HSJGxKomcNQXNS96sYHFzq4Q3BtiIfvBl8dS2EX1q/9KCHh24QpzUCeVnyAPNzbmxL7NAWxdDbKR7iLifWaOv6VFopt8aWSZAhwcMZwOSegn0D4hKPtNmZmD840z+QxmBnE84xzK2vZBzL4WiX9GRVQUwD6YeXo654YSg/FEcjCM8zYVI/yMq0mZeqDCTDD5c1TnmS2v3g4jki1oXJgJrwbcPg6H7G7HLJdSqEDOPAXQOoXWx4n+U8wiQsGUXIPQ/UBqJtB0swvNwSMFgAZSapylKwEDFbmFbk+y40GXuFBrTjyS6zR8hswAvaEidgu2V0AFL2CJ+tE9j4myjdwDeXWEp6rccBv8W2PuqIt6nQSESNUwacrxnvHUMy3Vt58EV8HaXJOVtkY0vA4lUtxJZUnxj6oJ4jbw5sOp1ebGhETKXd9eBDpA1KjO2AHHQBOjLqN9jrVsRrZuFtlMHLGNq3vv/B89fymKwxsFl30SrY5V4cv27qyxlG/d00EMrLHw6o5gHFm1rBFZuJasekQDVgzzeEF0JnsBZa9IO0Y0bcP8dpBeoxuE5LzfbEkVrOVNuK3eiDtVlDoCfCA/mbk51SH+oFkBKFQCZ8wWaWvNyZwetMWcnVYblKHWjDwqKV2ezU4GIvhYGGDah5O0Vq+8tU77PoVcmFg1DyYP5h+XO3NsoQyDig==
  template:
    metadata:
      name: navidrome-secrets
      namespace: media
