---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-plex-token
  namespace: homepage
spec:
  encryptedData:
    PLEX_TOKEN: AgCbcXWsd7bOGZM/XLWe43F9e5dTy4TZ1JbFavjKatIVW9OPIg1EEpMfehgPeqyesm9EuntEmBvV2PTdWhwAJnhTyNmj4XX1816yGysMPNKrZNyN4IPG3T+JBBvE93MFWGZeSOT4YSOo6X/XgdG1YY8usLm3qKzQ0O6lMbj6+mPtO2f2x6OMo1DkwElGIvKmrYzlIERLD6ex0h7YRXmI/xcHGfEMMxIZjwC3DOByOmxdVDjnZHruLz0wZfeX6klRBlIF9lUoTGqPd+eVWz233qmmfP5DbmGNLvT3wYbgFzorxXgDWUgApnZuB1n+1IilWDblZb+cbSbyouWGOXcvHy61+LxOSR3vouK5x9bGaQOFLuyDuYUwgaIuFncfTZIUio3PbDfzXZMCQAIYhe8CcryDEgSk5QJZ6L+TaV8NxJtKchWL8Gy/sMwNb1HCIkXVKa0NXY0UvZ/VxMdLForctJugO9/LnxLp9lRToeb34Mp58YlYeO2uPqqATIEcY5koTZU25DyDAxqs/KGpFQlZy4/kueLz2kUVCTO3DAnoNHTMhshcHu2/vHAS2v/vpl4eCOreQJjzs1Y1IZ+TpicuavKQIVCr6m1CS67+YccGjr138p+KmdV6ZE3MLe9Tm4hqY9yHXfultJcUJ74aAs8rDc4e1ijc3yq8Bg8fibOCtWrO6YmUpq9Rpzx0nxtFHHjvU9PH0nUo69KcObHHyvpjKS0T+EIbSw==
  template:
    metadata:
      name: homepage-plex-token
      namespace: homepage
