---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-technitium-token
  namespace: homepage
spec:
  encryptedData:
    TECHNITIUM_TOKEN: AgCoVxNUjRQAuIF6sb2jzmKv7UwicRRXYij3Tv7cmqW1QIcM7Ho07ItsTSdBK7IRlsSCwz4WRamUOPs3wXu7qwdwHlrS4X7Obc75swpsYPz6hL0uSD/WBVUoqQrzm2ohLSTdCLoX6GqcTD76B5BdQbeR4YwERlKP9KLb7JgbcdxZR9vZBeviJR646+Eh3bftxTTgX15O/us5cWiPUvTxb8INTtUemicscUC24ZdOuiP7WlS8HbMKCysub9CSDpPIsEJDx+Uqim82LU6wwiV0uVvjLsOGQv39F8ApLKLfmRSIRtGCUBHIN2sKQdiRExIcKqkM0zCrq3RFh/BtXdepKBSjin+PlSqRsGcL/u0HXTwcf6xFYUFpXK1jM9BFf/D1Rk3KwndSgOXX5zQGsHfSsXDTIXCtX4EeGdwe3siragpuET8hR3LAuQ/IlctlLPajsMz4iVowbETN2NiONaewUahjjkQ9J3rPAUc4WYOKPiiURfaSyE3zRcTfEjI3q3wdVBjJ3PmcoGGvRG+fUvEtWmMXcRcsdaZ+AoTQcADfsKCmWzlZ4hSJak15SRHeXw3wo0sJguXe57+HM5/yOEp3lEZRgPPQhl216x4HsoFrmx1P2xjjz1snZlfQt6HPRMIttg60cH6himqMjVldQ3+d9Ns5UrirO16c3opg//yLNZF2CUXFLpPwMSlejtum2N301rFOy6HAB37ULKil2AtYtdHBH8tiGCmPpCf1NNqYB7SAO3TFsH0bE9IC8JMRqLykuOLN8NB4Sf3SWBr0I/gIuKRH
  template:
    metadata:
      name: homepage-technitium-token
      namespace: homepage
